Unexpected end of input
On file `tests/errors/parse_error.vrv` at 1:4
1: foo(
      ^
